### ISSUE TITLE
Velocity dependency as optional

### ISSUE THREAD

**Issue by aleksandr-m** [struts-community-plugins/struts2-jquery#132] opened 2017-02-27 20:54 UTC
Can velocity dependency be declared as optional?

**Comment by flofourcade** [comment] 2017-03-31 08:24
Tested it, seems possible and even consistent with struts2-core where this dependency is optional.
Got to see the impact on the showcase apps where velocity is used to demonstrate the use of tags in vm templates.

**Comment by sdutry** [comment] 2017-03-31 18:45
@flofourcade 
The showcase works because the showcase itself has a dependency to velocity

**Comment by flofourcade** [comment] 2017-03-31 19:11
@sdutry ok, maybe it can be usefull to do the same thing in the bootstrap plugin ? It seems nowadays that velocity is less used, compared to freemarker and other templating engines.

**Comment by sdutry** [comment] 2017-03-31 20:52
@flofourcade 
I just checked it looks like the velocity dependency in the `struts2-bootstrap` plugin is already marked as optional.

```xml
        <dependency>
            <groupId>org.apache.velocity</groupId>
            <artifactId>velocity</artifactId>
            <version>1.7</version>
            <optional>true</optional>
        </dependency>
```

**Comment by flofourcade** [comment] 2017-04-03 06:33
@sdutry 
velocity-tools has a transitive dependency to velocity. There 's an exclude for it in the pom but it seems inefficient. Running maven dependency:tree on a project with bootstrap plugin or using an IDE (eg dependency hierarchy in Eclipse) shows that velocity is still included in classpath as a transitive dependency from velocity-tools.

```xml
<dependency>
            <groupId>org.apache.velocity</groupId>
            <artifactId>velocity-tools</artifactId>
            <version>2.0</version>
            <exclusions>
                <exclusion>
                    <groupId>javax.servlet</groupId>
                    <artifactId>servlet-api</artifactId>
                </exclusion>
                <exclusion>
                    <groupId>struts</groupId>
                    <artifactId>struts</artifactId>
                </exclusion>
                <exclusion>
                    <groupId>velocity</groupId>
                    <artifactId>velocity</artifactId>
                </exclusion>
            </exclusions>
        </dependency>
```

So we could

- fix the exclusion (I think changing groupId will work)
- find why velocity-tools is needed at runtime, and not only velocity at compile time like the other plugins.

**EDIT**

Just saw that jars from Struts 1 are also included by maven in the classpath (eg showcase )!!!
Definitly have to fix this

**Comment by jogep** [comment] 2018-01-01 15:58
Close issue because version 4.0.3 is released.

**Closed as completed by jogep** 2018-01-01 15:58 UTC
Labels: enhancement, resolved

**Comment by matorodriguez** [comment] 2018-01-05 01:15
Hi! This leads to exceptions based on the lack of commons-lang (witch at previous version was a dependency of velocity):

Caused by: java.lang.NoClassDefFoundError: org/apache/commons/lang/StringUtils
        at com.jgeppert.struts2.jquery.components.Head.evaluateParams(Head.java:194)

**I believe that commons-lang should be added as a direct dependency for struts2-jquery. And some day update to lang3 or just use java standards.**

**Comment by lukaszlenart** [comment] 2018-01-05 06:29
Switching to lang3 is a better option as Struts2 is using lang3 right now.

**Comment by matorodriguez** [comment] 2018-01-28 22:24
How should we handle this? New issue?
Thanks!

**Comment by aleksandr-m** [comment] 2018-01-29 13:22
@matorodriguez Yes, open new issue and reference this one, or better provide PR. :)

**Comment by matorodriguez** [comment] 2018-01-30 01:13
@aleksandr-m PR done #159
